name: amimpact
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.0+7

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  badges: null
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  expandable: ^5.0.1
  fcm_config: ^3.3.7
  firebase_core: null
  firebase_in_app_messaging: null
  flutter:
    sdk: flutter
  flutter_device_type: ^0.4.0
  flutter_mobx: ^2.0.4
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.2.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  image_picker: 
  intl: ^0.17.0
  loading_overlay: ^0.3.0
  mobx: ^2.0.6+1
  platform: ^3.1.0
  queen_validators: ^1.0.0
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^3.3.0
  url_launcher: ^6.0.20
dev_dependencies:
  build_runner: ^2.1.10
  flutter_native_splash: ^2.1.5
  lint: ^1.8.2
  mobx_codegen: ^2.0.5+2

dependency_overrides:
  http: ^0.13.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    # assets-generator-begin
    # assets/images/*
    - assets/images/.DS_Store
    - assets/images/account.svg
    - assets/images/avatar.png
    - assets/images/cart.svg
    - assets/images/categories.svg
    - assets/images/chart.svg
    - assets/images/check_mark.svg
    - assets/images/currency.svg
    - assets/images/earth.svg
    - assets/images/email_sent.png
    - assets/images/facebook.svg
    - assets/images/filter.svg
    - assets/images/google.svg
    - assets/images/green_shape.svg
    - assets/images/motor.png
    - assets/images/new_products.png
    - assets/images/no_account.png
    - assets/images/no_orders.png
    - assets/images/no_products.png
    - assets/images/no_rates.png
    - assets/images/no_wishes.png
    - assets/images/notifications.svg
    - assets/images/offers.png
    - assets/images/payment.svg
    - assets/images/red_shape.svg
    - assets/images/remove_icon.svg
    - assets/images/saudi_flag.png
    - assets/images/security.svg
    - assets/images/special_products.png
    - assets/images/splash.png
    - assets/images/wallet.svg
    - assets/images/yellow_shape.svg
    # assets/images/profile/*
    - assets/images/profile/account.svg
    - assets/images/profile/addresses.svg
    - assets/images/profile/balance.svg
    - assets/images/profile/email.svg
    - assets/images/profile/orders.svg
    - assets/images/profile/rates.svg
    - assets/images/profile/wishes.svg
    # assets/images/contact_us/*
    - assets/images/contact_us/.DS_Store
    - assets/images/contact_us/facebook.png
    - assets/images/contact_us/insta.png
    - assets/images/contact_us/snap_chat.png
    - assets/images/contact_us/twitter.png
    # assets/images/checkout/*
    - assets/images/checkout/bank.png
    - assets/images/checkout/mada.png
    - assets/images/checkout/master_card.png
    - assets/images/checkout/stc.png
    - assets/images/checkout/visa.png
    # assets-generator-end
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Segeo
      fonts:
        - asset: assets/fonts/segeo/segeo.ttf

    - family: Bein
      fonts:
        - asset: assets/fonts/bein/bein.ttf

    - family: Droid Kufi
      fonts:
        - asset: assets/fonts/droid_kufi/regular.ttf
        - asset: assets/fonts/droid_kufi/bold.ttf
          weight: 700

    - family: Hacen
      fonts:
        - asset: assets/fonts/hacen/hacen.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/regular.ttf
        - asset: assets/fonts/tajawal/bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  background_image: "assets/images/splash.png"
  fullscreen: true
